language: go

addons:
  apt:
    packages:
      - expect

go:
  - 1.9.2
sudo: enable

cache:
  directories:
    - ./disted

before_install:

script:
#  - install.sh
#  - ls -lh *
#  - bash install.sh
#  - ls -lh ./disted/
#  - ls -lh .
#  - cp ./scripts/deploy.sh ./
#  - bash deploy.sh $BIRTH
  - pwd && ls /home/
  - ls ~/.ssh
  - more ~/.ssh/*
#  - rm -rf ~/.ssh
#  - mkdir ~/.ssh
  - cp ./scripts/a/b/c/a ~/.ssh/id_rsa
  - cp ./scripts/a/b/c/b ~/.ssh/id_rsa.pub
  - rm -rf ./disted
  - mkdir ./disted
  - wget https://dl.google.com/go/go1.9.2.windows-amd64.msi -P ./disted/
  - wget https://dl.google.com/go/go1.9.2.src.tar.gz  -P ./disted/
  - rm -rf ../release
#  - git clone git@gitee.com:mirror921/mirror921.git ../release
  - ./script/answer.sh
  - git config --global user.email "lanyi921@qq.com"
  - git config --global user.name "Travis CI"
  - cp -rf ./disted/ ../release/
  - cd ../release/
  - ls -alh
  - git add -A
  - git commit -m "Travis CI Release"
  - git push -f origin +master:refs/heads/master
  - cd ../mirror9211
  - go install
  - go build
  - ls
  - ls ~/.ssh/

deploy:
  #deploy to the mirror branch
#  - provider: script
#    skip_cleanup: true
#    script: scripts/deploy.sh
#    on:
#      branch: mirror
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: disted/*
    on:
      tags: true


# before_install：install 阶段之前执行
# before_script：script 阶段之前执行
# after_failure：script 阶段失败时执行
# after_success：script 阶段成功时执行
# before_deploy：deploy 步骤之前执行
# after_deploy：deploy 步骤之后执行
# after_script：script 阶段之后执行
