language: go

go:
  - 1.9.2
sudo: enable

cache:
  directories:
    - ./disted

before_install:

script:
#  - install.sh
  - mkdir disted && bash install.sh
  - ls -lh ./disted/
  - ls -lh .
  - cd ./disted/
  - cp ../scripts/deploy.sh ./
  - bash deploy.sh $BIRTH
  - cd ..
  - go install
  - go build

deploy:
  #deploy to the mirror branch
#  - provider: script
#    skip_cleanup: true
#    script: scripts/deploy.sh
#    on:
#      branch: mirror
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: disted/*
    on:
      tags: true


# before_install：install 阶段之前执行
# before_script：script 阶段之前执行
# after_failure：script 阶段失败时执行
# after_success：script 阶段成功时执行
# before_deploy：deploy 步骤之前执行
# after_deploy：deploy 步骤之后执行
# after_script：script 阶段之后执行
